from manim import *

class animations(Scene):
    def construct(self):
       self.clear()
       stroke1 = Line(UP,LEFT+2*DOWN)
       stroke2 = stroke1.copy()
       self.play(Create(stroke1))
       stroke3 = Line(stroke1.get_center()*LEFT,stroke2.get_center()*RIGHT)
       stroke3.rotate(180*DEGREES,Z_AXIS,ORIGIN)
       self.play((Rotate(stroke2,180*DEGREES,axis=UP,about_point=ORIGIN)),Create(stroke3))
       Letter=VGroup(stroke1,stroke2,stroke3)
       self.wait()
       self.play(Rotate(Letter,20*DEGREES,Z_AXIS))
       self.play(Rotate(stroke3,-20*DEGREES,Z_AXIS))
       curve1 = ArcBetweenPoints(stroke1.get_start(),stroke3.get_end(),-PI)
       curve2 = ArcBetweenPoints(stroke3.get_end(),stroke1.get_end(),-PI)
       self.play(Transform(stroke2,curve1))
       self.remove(curve1)
       self.play(Create(curve2))
       self.wait()
       self.play(Uncreate(stroke1),Uncreate(stroke3))
       self.play(Uncreate(stroke2),Rotate(curve2,15*DEGREES))
       self.play(ScaleInPlace(curve2,1.5))
       self.wait()
       d_line = Line(curve2.get_start()*UP,curve2.get_end())
       self.play(Create(d_line))
       d =  VGroup(d_line,curve2)
       self.play(Rotate(d,16*DEGREES))
       self.wait()
       self.play(Uncreate(curve2))
       e_line1 = Line(d_line.get_start(),d_line.get_start()+1*LEFT)
       e_line2 = Line(d_line.get_center(),d_line.get_center()+0.75*LEFT)
       e_line3 = Line(d_line.get_end(),d_line.get_end()+1*LEFT)
       self.play(Create(e_line1),Create(e_line2),Create(e_line3))
       e = VGroup(d_line,e_line1,e_line2,e_line3)
       self.play(Rotate(e,180*DEGREES,Y_AXIS))
       self.wait()
       self.play(Uncreate(e_line3))
       self.wait()